# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MissionToolkit < Formula
  desc ""
  homepage ""
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v1.1.3/mission-toolkit_Darwin_x86_64.zip"
      sha256 "d27b6b70f24c1ab33e7e70ae2c82b9d2bc2da05dfb7928cb8ecc501eff2f9a29"

      def install
        bin.install "m"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v1.1.3/mission-toolkit_Darwin_arm64.zip"
      sha256 "5728f711d037993ff435ed41671c4d9460f4f5c61f2d04bd5072911e48206b2d"

      def install
        bin.install "m"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v1.1.3/mission-toolkit_Linux_x86_64.zip"
      sha256 "e01807fdf285c8c3a494e26c34fdb222d976233550675d1a27d8069da6d99087"
      def install
        bin.install "m"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v1.1.3/mission-toolkit_Linux_arm64.zip"
      sha256 "17840a5186dc46c585d890b57052974ca2fd6b1038bc98b1a85fa7c3a7473a99"
      def install
        bin.install "m"
      end
    end
  end
end
