# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MissionToolkit < Formula
  desc ""
  homepage ""
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v1.1.3/mission-toolkit_Darwin_x86_64.zip"
      sha256 "d2f5b3f35bb6f979cc45acdd47d63b24419b57ab486542e2f85ba1fb43d5317f"

      def install
        bin.install "m"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v1.1.3/mission-toolkit_Darwin_arm64.zip"
      sha256 "25fdd1ed6ff6f71b28251c335a4831a11638b76c2337e31d7297bd9fa037eae1"

      def install
        bin.install "m"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v1.1.3/mission-toolkit_Linux_x86_64.zip"
      sha256 "31b8cbad8a2d0c18a9228a58cbda3e6da4ab37f4ccc36571d3aa48310bd7257e"
      def install
        bin.install "m"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v1.1.3/mission-toolkit_Linux_arm64.zip"
      sha256 "7c301cbfc661677980862524d34d14b891c2b700cfcc4bc7b0d7357b27e7b249"
      def install
        bin.install "m"
      end
    end
  end
end
