# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MissionToolkit < Formula
  desc ""
  homepage ""
  version "2.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v2.3.1/mission-toolkit_Darwin_x86_64.zip"
      sha256 "1b29c285a7206034d525bacf2aef77345d29b6e20ef75f03514efd8934e3801c"

      def install
        bin.install "m"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v2.3.1/mission-toolkit_Darwin_arm64.zip"
      sha256 "f0a933c1372c9eeaded91bd16e3cd50eda1247d2f667d4f5a3ca64a4be85dc31"

      def install
        bin.install "m"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v2.3.1/mission-toolkit_Linux_x86_64.zip"
      sha256 "8dd3bd90fcae886b8db5f51ca7cc0cbc24a011d9021ed3348e7eeb07a47f42f7"
      def install
        bin.install "m"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v2.3.1/mission-toolkit_Linux_arm64.zip"
      sha256 "890b14fe5e2bea48e09fdf2709b542467fcd7cea7370cc27ef4931fd4df3a679"
      def install
        bin.install "m"
      end
    end
  end
end
