# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MissionToolkit < Formula
  desc ""
  homepage ""
  version "2.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v2.1.0/mission-toolkit_Darwin_x86_64.zip"
      sha256 "3441d995cdb72c7a6d92f29b2550ccd20bc1adda0840444a7d726286612bddad"

      def install
        bin.install "m"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v2.1.0/mission-toolkit_Darwin_arm64.zip"
      sha256 "53c60dfbaab30778f06fbacfb0de51414da6d5527f88cb55dd5257e8049e3775"

      def install
        bin.install "m"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v2.1.0/mission-toolkit_Linux_x86_64.zip"
      sha256 "9a97c4b2b22cff0f7a3be74dee9becf7309c3ebc5b1dd48da78211d3ff2ff896"
      def install
        bin.install "m"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnatag/mission-toolkit/releases/download/v2.1.0/mission-toolkit_Linux_arm64.zip"
      sha256 "25fed4d99a8b757f56c846d3c48d9a0fa32c2c53cbb3a7754f2071ad0a2b635c"
      def install
        bin.install "m"
      end
    end
  end
end
